apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: kela-wind-turbine-jkl
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: kela-wind-turbine-jkl
    app.kubernetes.io/part-of: kela-wind-turbine
  name: kela-wind-turbine-jkl
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: kela-wind-turbine-jkl
status:
  loadBalancer: {}
